name: Trigger Profile Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Signal Profile Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/psycho237-prog/psycho237-prog/dispatches \
            -d '{"event_type": "update-profile", "client_payload": {"repository": "'"$GITHUB_REPOSITORY"'"}}'
